# Generated by Django 5.1.3 on 2025-01-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
